### ISSUE TITLE
Incompatible responses window may be too tall for screen

### ISSUE THREAD

**Issue by sroracle** [gruepr/gruepr#1]
Howdy,

I believe you had advertised this software on Reddit a few weeks ago and I have to say that I'm quite impressed. There is one small issue I have encountered recently with it, however.

If the number of unique responses for a particular attribute is large enough, then the incompatible attributes window will be too tall to fit on the screen. This would be OK if there was some way to scroll through the window, but there is not. Please see the screenshot below:

![image](https://user-images.githubusercontent.com/118271/187038538-59a78c36-c930-4f44-8479-78dd76532235.png)

**Comment by joshuahertz** [comment]
The UI on the dialog window to collect Incompatible Attributes (and also the Required Attributes) has been updated in the code and will be included in the next release.

**Comment by joshuahertz** [comment]
Version 11.1 was just released with this bugfix included. Thank you for submitting this issue.
