### ISSUE TITLE
window sizing manually adding/editing students (create teams)

### ISSUE THREAD

**Issue by ajdungan** [gruepr/gruepr#2]
No ability to vertically resize window while manually editing or adding students and window extends in negative space/beyond screen accessibility. (my screen size is 1920x1080, and OS: windows 10)

![grueprwindow](https://user-images.githubusercontent.com/36718949/194920397-468c8238-7524-4bff-8b92-6eda8f7d64d6.PNG)

**Comment by ajdungan** [comment]
When smaller classes (working with class of 11 students) this window is sized appropriately and is able to be vertically resized. I saw this issue in my larger class of ~21 , (but it is still functional with the keybord/enter/esc)

**Comment by joshuahertz** [comment]
Thank you. A nearly identical issue with a different dialog box was fixed in the most recent version. The same fix will be brought to this dialog in the next version.

**Comment by joshuahertz** [comment]
Fixed in the code base and will be included in next release.

**Comment by joshuahertz** [comment]
Version 11.1 was just released with this bugfix included. Thank you for submitting this issue.
