### ISSUE TITLE
Timezone translation in times/hours not included in survey

### ISSUE THREAD

**Issue by ajdungan** [gruepr/gruepr#3]
## Timezone translation doesn't function for times/hours not included in survey

In my survey I ask available times from 6 AM to 11PM, I have students all around the world and am also surveying their time zones, gruepr is mostly translating their local time zone to the base/class time zone correctly except when their timezone adjusted availability spills into hours 12 AM to 5 AM (ie times not included my survey). 
For example, a student in S. Africa is +7 hours ahead of the class timezone and lists their ability for 10 PM (4 AM class timezone) and this availability is excluded because it wasn't included in the original survey.

## my temporary workaround
I manually added a dummy student into the survey spreadsheet and listed all the times/hours available not included in the original survey (12 AM to 5AM) as their availability. Then to cancel out having the dummy student assigned to a group and influencing group selection process I adjusted custom team sizes to have a single group of one and then added a few prevented teammates with the dummy student, this forced the dummy student into its own lonely group. After doing this all the students' availability were correctly translated for all 24 hours.

Thanks for this wonderful software! The timezone functionality has been a huge help for me!

**Comment by joshuahertz** [comment]
A fix is already in progress and will be incorporated into the next version.

**Comment by joshuahertz** [comment]
Fixed in the code base; will be included in next release.

**Comment by joshuahertz** [comment]
Version 11.1 was just released with this bugfix included. Thank you for submitting this issue.
