### ISSUE TITLE
Loading prevented teammates from survey breaks if student names contains "and"

### ISSUE THREAD

**Issue by sroracle** [gruepr/gruepr#4]
In `studentRecord.cpp`, [line 270](https://github.com/gruepr/gruepr/blob/master/studentRecord.cpp#L270) reads:

```c++
        prefNonTeammates.replace(QRegularExpression("\\s*([,;&]|(?:and))\\s*"), "\n");     // replace every [, ; & and] with new line
```

If the student's name contains the string `and`, this will insert a newline in the middle of their name, which will then prevent matching that student's name later on.

The same issue appears to affect the preferred teammates option, but I do not use it.

For my own purposes I've just removed the `|(?:and)` part of the regular expression for now, but something like `|(?:\\s+and\\s+)` (to ensure at least one whitespace character on either side of the word "and") might work.

**Comment by joshuahertz** [comment]
Excellent point. I will incorporate into the next version.

**Comment by sroracle** [comment]
Thanks!

**Comment by joshuahertz** [comment]
Version 11.1 was just released with this bugfix included. Thank you for submitting this issue.
