### ISSUE TITLE
Cannot create Google form

### ISSUE THREAD

**Issue by warrenallen** [gruepr/gruepr#5]
Canvas survey creation seems to work, but not Google forms. I'm running the latest version of gruepr on MacOS. I have tried two different Google accounts, and I have tried with Safari and Firefox. In both cases, after the Google authentication prompts, there is an error. 

- Using Firefox as the browser: "Sorry, something went wrong there. Try again."
- Using Safari: "Safari Can't Conect to the Server" and "Safari can't open the page 127.0.0.1[...] because Safari can't connect to the server 127.0.0.1"

**Comment by joshuahertz** [comment]
I'm having trouble re-creating this issue. I suspect it might be security settings on the local computer.

**Comment by warrenallen** [comment]
> I'm having trouble re-creating this issue. I suspect it might be security settings on the local computer.

Could be. I'll try it on another machine when I have time. For now I'm doing fine with a Qualtrics survey based on the text output. Worked really well to create groups for my large class. thanks for the great catme alternative.

**Comment by joshuahertz** [comment]
Glad you find it useful. For the other side of catme--the peer and self evaluation, I use another free service: [TEAMMATES](https://teammatesv4.appspot.com)
